### ISSUE TITLE
Tracking issue: audit of all conversion errors.

### ISSUE THREAD

**Issue by carllerche** [hyperium/http#52]
The style used for conversion errors has not been consistent across the library. A full audit should be performed and error types should be normalized.

Known issues:

* [ ] name error after conversion fn (`FromStrError`) or after error semantics (`InvalidUri`)
* [ ] Should error types include the conversion input
* [ ] Should multiple types share the same error type. (`uri::Authority`, `uri::Path` both use `FromStrError`, yet the potential error cases don't fully overlap).
* [ ] Other issues not mentioned...

Relates: #48, #23
